name:                sudokusolver
version:             0.1.0.0
github:              "githubuser/sudokusolver"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/sudokusolver#readme>

dependencies:
- base >= 4.7 && < 5
- time
- deepseq

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -fllvm

library:
  source-dirs: src
  exposed-modules:
    - Lib
  dependencies:
    - base

executables:
  sudokusolver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudokusolver

tests:
  sudokusolver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudokusolver
    - HUnit

benchmarks:
  sudokusolver-bench:
    main:                Benchmark.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudokusolver
    - criterion
    - deepseq
    - base
