name: GameOfLife
version: 0.1.0.0
github: ""
license: BSD3
author: "Anonymous"
maintainer: "anonymous@example.com"
copyright: "2025 Anonymous"

extra-source-files:
- README.md

description: A Conway's Game of Life implementation in Haskell

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.7
- QuickCheck

library:
  source-dirs: src

executables:
  GameOfLife-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GameOfLife

tests:
  GameOfLife-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GameOfLife
    - hspec
    - QuickCheck
